let shopItemsData = [
    {
      id: "jfhgbvnscs",
      name: "Lipstick",
      price: 45,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-1.avif",
    },
    {
      id: "ioytrhndcv",
      name: "BB Cream",
      price: 78,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-2.avif",
    },
    {
      id: "wuefbncxbsn",
      name: "Cleansing oil",
      price: 20,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-3.avif",
    },
    {
      id: "thyfhcbcv",
      name: "Mascara",
      price: 21,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-4.avif",
    },
    {
      id: "thiecbawdjksadjk",
      name: "Eyeliner",
      price: 25,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-5.avif",
    },
    {
      id: "iuertrywebncdjksadjk",
      name: "Face Powder",
      price: 90,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-6.avif",
    },
    {
      id: "thierytbvcbvzdhadjk",
      name: "Eye Shadow",
      price: 36,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-7.avif",
    },
    {
      id: "trfoiwfcnbcawdjksadjk",
      name: "Nail Paint",
      price: 45,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-8.avif",
    },
    {
      id: "cbvxbcvsceldk",
      name: "Makeup Brush",
      price: 85,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-9.avif",
    },
    {
      id: "oiopijmjkhuihb",
      name: "Concealer",
      price: 120,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-10.avif",
    },
    {
      id: "oiopijewyiohbjhib",
      name: "Makeup Mirror",
      price: 35,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-11.avif",
    },
    {
      id: "rtytytuyuytyytbvncv",
      name: "Body Perfume",
      price: 350,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-12.avif",
    },
  ];